app/models/channels.py
from datetime import datetime
from email.utils import parsedate_to_datetime

import requests
from bs4 import BeautifulSoup

from app import get_db


class Channel:
    id: int
    title: str
    url: str

    def update_items(self):
        items = fetch_items(self.url)
        connection = get_db()
        cursor = connection.cursor()
        for item in items:
            cursor.execute(
                "insert or ignore "
                "into item (title, guid, link, description, publication_date, channel_id) "
                "values (?, ?, ?, ?, ?, ?)",
                (item.title, item.guid, item.link, item.description, item.publication_date, self.id))
        cursor.close()
        connection.commit()

    def find_all_items(self):
        connection = get_db()
        cursor = connection.cursor()
        cursor.execute(
            "select title, guid, link, description, publication_date "
            "from item "
            "where item.channel_id = ? "
            "order by publication_date desc",
            (self.id,))
        rows = cursor.fetchall()

        items = []
        for row in rows:
            item = Item()
            item.title = row[0]
            item.guid = row[1]
            item.link = row[2]
            item.description = row[3]
            item.publication_date = datetime.fromisoformat(row[4])
            item.channel_id = self.id
            items.append(item)
        return items


def find_all_channels():
    cur = get_db().cursor()
    cur.execute("select id, title, url from channel")
    rows = cur.fetchall()
    cur.close()

    channels = []
    for row in rows:
        channel = Channel()
        channel.id = row[0]
        channel.title = row[1]
        channel.url = row[2]
        channels.append(channel)

    return channels


def find_channel_by_id(channel_id) -> Channel:
    cur = get_db().cursor()
    cur.execute("select id, title, url from channel where channel.id = ?", (channel_id,))
    row = cur.fetchone()
    cur.close()

    channel = Channel()
    channel.id = row[0]
    channel.title = row[1]
    channel.url = row[2]

    return channel


def insert_new_channel(title, url) -> Channel:
    connection = get_db()
    cur = connection.cursor()
    cur.execute("insert into channel (title, url) values (?, ?)", (title, url))
    channel_id = cur.lastrowid
    cur.close()
    connection.commit()

    channel = Channel()
    channel.id = channel_id
    channel.title = title
    channel.url = url

    return channel


class Item:
    title: str
    guid: str
    link: str
    description: str
    publication_date: datetime
    channel_id: int


def convert_xml_to_item(xml_object) -> Item:
    item = Item()
    item.title = xml_object.title.text
    item.guid = xml_object.guid.text
    item.link = xml_object.link.text
    item.description = xml_object.description.text
    item.publication_date = parsedate_to_datetime(xml_object.pubDate.text)
    return item


def fetch_definition(url):
    channel_xml = fetch_xml_definition_object(url)

    channel = Channel()
    channel.id = None
    channel.url = channel_xml.link.text
    channel.title = channel_xml.title.text

    return channel


class SubscriptionError(Exception):
    pass


class ProvidedUrlIsNotRss(SubscriptionError):
    pass


class ProvidedUrlUnreachable(SubscriptionError):
    pass


def fetch_xml_definition_object(url):
    try:
        definition_text = requests.get(url).text
    except requests.exceptions.RequestException as exception:
        raise ProvidedUrlUnreachable(f"The URL ‘{url}’ is unreachable") from exception

    soup = BeautifulSoup(definition_text, features="xml")
    if soup.rss and soup.rss.channel:
        channel_xml = soup.rss.channel
        return channel_xml
    else:
        raise ProvidedUrlIsNotRss(f"There is no RSS definition at URL ‘{url}’")


def fetch_items(url):
    channel_xml = fetch_xml_definition_object(url)
    xml_items = channel_xml.find_all('item')
    return [convert_xml_to_item(item) for item in xml_items]


def subscribe(url) -> Channel:
    channel_definition = fetch_definition(url)
    channel = insert_new_channel(title=channel_definition.title, url=url)
    channel.update_items()
    return channel


def delete_channel_and_its_items(channel_id):
    connection = get_db()
    cur = connection.cursor()
    cur.execute("delete from item where channel_id=?", (channel_id,))
    cur.execute("delete from channel where id=?", (channel_id,))
    cur.close()
    connection.commit()
    return None

app/__init__.py
import sqlite3

from flask import Flask, g, app


def get_db():
    db = getattr(g, '_database', None)
    if db is None:
        db = g._database = sqlite3.connect(app.config['DATABASE'])
    return db


def close_connection(sender, **extra):
    db = getattr(g, '_database', None)
    if db is not None:
        db.close()


app.appcontext_tearing_down.connect(close_connection)

from . import models
from .views.library import library
from .views.home import home
from .views.channel import blueprint

app = Flask(__name__)
app.config.from_object('config')

app.register_blueprint(home)
app.register_blueprint(library, url_prefix='/library')
app.register_blueprint(blueprint, url_prefix='/channel')

app/views/channel.py
from flask import Blueprint, render_template, flash, redirect, url_for, request

from app.pagination import paginate
from app.models import channels as model

blueprint = Blueprint('channel', __name__)


@blueprint.route('/<channel_id>')
def display(channel_id):
    page_ordinal = int(request.args.get('page') or 1)
    channel = model.find_channel_by_id(channel_id)
    items = channel.find_all_items()
    page = paginate(items, page_ordinal)
    return render_template('channel/display.html', channel=channel, page=page)


@blueprint.route('/<channel_id>/update', methods=['POST'])
def update(channel_id):
    channel = model.find_channel_by_id(channel_id)
    channel.update_items()
    flash(f"Channel ‘{channel.title}’ was successfully updated.")
    return redirect(url_for('channel.display', channel_id=channel_id))


@blueprint.route('/<channel_id>/unsubscribe', methods=['POST', 'DELETE'])
def unsubscribe(channel_id):
    channel = model.find_channel_by_id(channel_id)
    model.delete_channel_and_its_items(channel_id)
    flash(f"Successfully unsubscribed from channel ‘{channel.title}’.")
    return redirect(url_for('library.display'))

app/views/home.py
from flask import Blueprint, redirect, url_for

home = Blueprint('home', __name__)


@home.route('/')
def index():
    return redirect(url_for('library.display'))

app/views/library.py
from ast import dump

import flask
from flask import Blueprint, render_template, request, flash, redirect, url_for, get_flashed_messages

from app.models import channels as model
from app.models.channels import SubscriptionError

library = Blueprint('library', __name__)


@library.route('/')
def display():
    feeds = model.find_all_channels()
    return render_template('library/display.html', channels=feeds)


@library.route('/new')
def new():
    return render_template('library/new.html')


@library.route('/subscribe', methods=['POST'])
def subscribe():
    try:
        url = request.form['url']
        channel = model.subscribe(url)
        flash(f"Added subscription to channel ‘{channel.title}’.")
        return redirect(url_for('library.display'))
    except SubscriptionError as err:
        flash(f"Failed to add subscription: {err}", category='error')
        return redirect(url_for('library.new'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %} &ndash; Retrogress</title>
        <link rel="stylesheet" href="../static/base.css">
    {% endblock %}
</head>
<body>
{% block header %}
    <header>
        <h1><a href="{{ url_for('home.index') }}">Retrogress</a></h1>
        <h2>a simple RSS reader</h2>
    </header>
{% endblock %}
<main>
    {% if get_flashed_messages() %}
        <section id="flashed-messages">
            {% for category, message in get_flashed_messages(with_categories=True) %}
                <article class="{{ category }} message">
                    <h1 class="message-title">{{ category | capitalize }}</h1>
                    <p class="message-text">{{ message }}</p>
                </article>
            {% endfor %}
        </section>
    {% endif %}

    {% block main %}
    {% endblock %}
</main>
<footer>
    <p> Retrogress — an RSS aggregator <br> &copy; Egor Dubenetskiy, 2019</p>
</footer>
</body>
</html>

app/templates/channel/display.html
{% extends 'base.html' %}
{% block title %}
    {{ channel.title }}
{% endblock %}
{% block header %}
    <header class="channel-header">
        <p>
            <a href="{{ url_for('library.display') }}">&longleftarrow; Back to Library</a>
        </p>
        <h1>{{ channel.title }}</h1>
        <p>Total {{ page.total_items }} posts on {{ page.total_pages }} pages.</p>
        <p>Fetched from: <a href="{{ channel.url }}"><code>{{ channel.url }}</code></a></p>
        <form action="">
            <button formaction="{{ url_for('channel.update', channel_id=channel.id) }}"
                    formmethod="post"
                    class="primary button" type="submit">
                Refresh
            </button>
            <button formaction="{{ url_for('channel.unsubscribe', channel_id=channel.id) }}" formmethod="POST"
                    class="destructive button" type="submit">
                Unsubscribe
            </button>
        </form>
    </header>
{% endblock %}
{% block main %}
    <section class="channel-view">
        <main>
            {% if page.items %}
                {% for item in page.items %}
                    <article class="channel-item">
                        <header>
                            <h1>
                                <a href="{{ item.link }}" target="_blank">{{ item.title }}</a>
                            </h1>
                        </header>
                        <main>
                            <p>{{ item.description | safe }}</p>
                        </main>
                        <footer>
                            <p>{{ item.publication_date.strftime('%Y-%m-%d %H:%M %Z') }}</p>
                        </footer>
                    </article>
                {% endfor %}
            {% else %}
                <p>No items yet.</p>
            {% endif %}
        </main>
        <nav>
            <p>Pages:
                {% for page_number in range(1, page.total_pages + 1) %}
                    {% if page_number == page.ordinal %}
                        <span class="active page">{{ page_number }}</span>
                    {% else %}
                        {% set page_url = url_for('channel.display', channel_id=channel.id, page=page_number) %}
                        <a class="page button" href="{{ page_url }}">{{ page_number }}</a>
                    {% endif %}
                {% endfor %}
            </p>
        </nav>
    </section>
{% endblock %}

app/templates/library/display.html
{% extends('base.html') %}
{% block title %}
    Main Page
{% endblock %}
{% block main %}
    <section id="my-channels">
        <h1>Feeds</h1>
        {% if channels %}
            <ol id="my-channels-list">
                {% for channel in channels %}
                    <li>
                        <h2>
                            <a href="{{ url_for('channel.display', channel_id=channel.id) }}">{{ channel.title }}</a>
                        </h2>
                        <code>{{ channel.url }}</code>
                    </li>
                {% endfor %}
            </ol>
        {% else %}
            <p>You have not subscribed to any feeds yet.</p>
        {% endif %}
        <a href="{{ url_for('library.new') }}" class="button primary">Add new subscription</a>
    </section>
{% endblock %}

app/templates/library/new.html
{% extends('base.html') %}
{% block title %}
    New Subscription
{% endblock %}
{% block main %}
    <section>
        <h1>Add New Subscription</h1>
        <form class="flex" action="{{ url_for('library.subscribe') }}" method="post">
            <label>
                <span>URL</span>
                <input type="url" name="url" placeholder="Enter URL of a RSS feed here" required>
            </label>
            <p>
                <button class="primary button" type="submit">
                    Subscribe
                </button>
            </p>
        </form>
    </section>
{% endblock %}